name: Continuous Integration

on:
  push:
    branches:
      - main
      - slave
      - slave2
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r py_action/requirements.txt

      - name: Run unit tests
        run: python -m unittest discover

      - name: Create new branch
        run: git checkout -b feature-branch

      - name: Make changes to code
        run: |
          # Make changes to code here

      - name: Commit changes
        run: |
          git add .
          git commit -m "Update code"
          git push origin feature-branch

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update code"
          title: "Update code"
          body: "This PR updates the code."
          branch: feature-branch
          base: main

      - name: Merge Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = context.payload.pull_request.number;
            const response = await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number
            });
            console.log(response);
